### ISSUE TITLE
missing requirements file and lack of dependency packaging

### ISSUE THREAD

**Issue by fcakyon** [itsmehemant7/PyMovieDb#2]
Thanks for the great package! I am facing some issues:

## env

windows10, python3.10, miniconda env

## steps

```bash
pip install PyMovieDb 
```

```python
from PyMovieDb import IMDB

imdb = IMDB()
res = imdb.get_by_id("asdsad")
```

## error

```bash
Traceback (most recent call last):
  File "...\lib\site-packages\PyMovieDb\__init__.py", line 2, in <module>
    from .imdb import IMDB
  File "...\lib\site-packages\PyMovieDb\imdb.py", line 5, in <module>
    from requests_html import HTMLSession
ModuleNotFoundError: No module named 'requests_html'
```

**Comment by de-Generation** [comment]
install **requests-html** module then:

`pip3 install requests-html`

**Comment by fcakyon** [comment]
@itsmehemant7 @de-Generation, it should be added to package requirements in setup.py https://github.com/itsmehemant7/PyMovieDb/blob/master/setup.py

Manually installing dependencies is not a good practice.

**Comment by itsmehemant7** [comment]
requirements are added in the setup.py
