### ISSUE TITLE
get() returns json dump instead of dict

### ISSUE THREAD

**Issue by fcakyon** [itsmehemant7/PyMovieDb#3]
Thanks for all the effort, I just started utilizing your package in one of my works!

In most apis, data is returned as a dict instead of json dump. However in your work, I manually convert your method outputs to a dict at every call.

Do you have any intentions to update the get() output so that it returns a dict instead of json dump?

https://github.com/itsmehemant7/PyMovieDb/blob/40e37ab83616a5a7b1abe7b1a958dae3f722e0c6/build/lib/PyMovieDb/imdb.py#L188

**Comment by iamgojoof6eyes** [comment]
Thank you for creating this issue. I was just about to make this one

**Comment by iamgojoof6eyes** [comment]
However, I just found a solution to it
```python
import json
res = imdb.get_by_name("Loki")
res = json.load(res)
```
or 
```python
import ast
res = imdb.get_by_name("Loki")
res = ast.literal_eval(res)
```
I have tried the second one and it worked for me. I have also tried 1st one but it isn't working for me at least 

[Context](https://www.geeksforgeeks.org/python-convert-string-dictionary-to-dictionary/)


Hope it would help

**Comment by fcakyon** [comment]
@iamgojoof6eyes thanks for your workaround but it would be easier if the original output returned a dict. What do you think about it? @itsmehemant7

**Comment by iamgojoof6eyes** [comment]
Necessary indeed. While using it sometimes it throws errors while running the code.

**Comment by itsmehemant7** [comment]
@iamgojoof6eyes thanks for the issue(s)....will fix in next version ASAP.

**Comment by fcakyon** [comment]
@itsmehemant7 thanks a lot! Can you also address this issue? https://github.com/itsmehemant7/PyMovieDb/issues/2

**Comment by itsmehemant7** [comment]
OK...PyMovieDb is designed for web app implementation, you can directly make calls from the front-end to the API easily. Although this is not a blocker, if you need output as `dict` then simply use `output_dict= json.loads(API_response)`

**Comment by samarthdave** [comment]
Hi, can you make this more apparently in the README? I copied the result of `imdb.get_by_id("tt4807830")` (Bullet Train) from the README into ChatGPT and asked it to write a script for my Notion page.

I whole heartedly trusted the output (yeah i know). Then, I spent 10 minutes wondering why I couldn't index on the result object:
```python
>>> res = imdb.get_by_id("tt12593682")
# { Bullet Train ... }
>>> res['name']
# ??? *confused*
>>> type(res)
<class 'str'> *ohhhh* *realizes*
```

How does adding an optional kwarg that bypasses the json dump sound? Something like this:
```python
imdb.get_by_id("tt12593682", dump=True)
```

**Comment by fcakyon** [comment]
@samarthdave i honestly dont understand why he refuses to add such a feature.
