### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by iamgojoof6eyes** [itsmehemant7/PyMovieDb#4]
Sometimes, `get_by_name()` doesn't work. It returns no results even for famous movies like Deadpool, and Avengers Endgame.

**Comment by itsmehemant7** [comment]
@iamgojoof6eyes PyMovieDb is based on web scraping, show some mercy to the main website i.e imdb.com... IMDB will not return desired response if you make a lot of requests simultaneously without any delay. Just keep some delay (like humans do) between requests.
**Tip:** If you are using it with Django or Flask i.e. web app then (must) use cache to store the results (store the result if you got a 200 status code from API) for a few minutes.
