### ISSUE TITLE
Not fixed!

### ISSUE THREAD

**Issue by iamgojoof6eyes** [itsmehemant7/PyMovieDb#5]
issue #3 is not really fixed...it is still returning string not dict as result. I have compared the 0.0.6 release with the previous one and you haven't changed a thing, so how in the world did the issue get fixed? @itsmehemant7 

[![pic](https://te.legra.ph/file/a33d35b53c1afe66a316f.jpg)](https://te.legra.ph/file/a33d35b53c1afe66a316f.jpg)

[![pic2](https://te.legra.ph/file/bfec9daa880f17d3ce9cd.jpg)](https://te.legra.ph/file/bfec9daa880f17d3ce9cd.jpg)

[![pic3](https://te.legra.ph/file/9a6be87f8ba4d60722174.jpg)](https://te.legra.ph/file/9a6be87f8ba4d60722174.jpg)

**Comment by itsmehemant7** [comment]
[https://github.com/itsmehemant7/PyMovieDb/issues/3#issuecomment-1327917692](url)

**Comment by itsmehemant7** [comment]
@iamgojoof6eyes  [https://github.com/itsmehemant7/PyMovieDb/issues/3#issuecomment-1327917692](https://github.com/itsmehemant7/PyMovieDb/issues/3#issuecomment-1327917692) see

**Comment by iamgojoof6eyes** [comment]
> @iamgojoof6eyes [#3 (comment)](https://github.com/itsmehemant7/PyMovieDb/issues/3#issuecomment-1327917692) see

that's the point some times it is not working

**Comment by iamgojoof6eyes** [comment]
@itsmehemant7 oh sorry I missed that comment :sweat_smile:
